site_name: OpenEMP
theme:
  name: material
  language: en
  logo: assets/images/openemp.svg
  palette:
    primary: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
markdown_extensions:
  - pymdownx.emoji
  - admonition
  - codehilite
  - toc:
      toc_depth: 3
nav:
  - Getting started: 'index.md'
  - About OpenEMP:
    - Community: 'about/community.md'
    - OpenEMP Architecture: about/core.md
    - How To Contribute: 'about/how-to-contribute.md'
    - Code of conduct: about/code-of-conduct.md
    - License: 'about/license.md'
  - Developer Guide: 
    - Guidelines: 'dev/guidelines.md'
    - Services :
      - Service definition: services/index.md
      - OpenEMP User: 'services/user.md'
