name: Build

on: [push, pull_request]

jobs:
  build-doc:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: Install requirements
        run:
          pip install -r docs/requirements.txt

      - name: Build documentation
        env:
          LC_ALL: C.UTF-8
          LANG: C.UTF-8
        run:
          mkdocs build
